# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarrotMarket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod "Texture"
	pod 'RxSwift', '6.2.0'
        pod 'RxCocoa', '6.2.0'

  # Pods for CarrotMarket

  target 'CarrotMarketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarrotMarketUITests' do
    # Pods for testing
  end

end
